### ISSUE TITLE
wiki mirrors are missing all lowercase wiki pages

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/mirror#15]
It looks like all the uppercase pages are in the mirrors but not the lowercase named pages.

Digging in it's actually that the wiki_dump is crashing on the filename length. 

```
Writing "Tutorials(2f)Landing(20)an(20)autonomous(20)UAV(20)on(20)a(20)moving(20)platform(20)using(20)only(20)a(20)front(20)facing(20)camera.html"...
Writing "Tutorials(2f)Landing(20)an(20)autonomous(20)UAV(20)on(20)a(20)moving(20)platform(20)using(20)only(20)a(20)front(20)facing(20)camera(2f)Landing(20)an(20)autonomous(20)UAV(20)on(20)a(20)moving(20)platform(20)using(20)only(20)a(20)front(20)facing(20)camera.html"...
Traceback (most recent call last):
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/moin.py", line 24, in <module>
    run()
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/moin.py", line 15, in run
    MoinScript().run(showtime=0)
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/__init__.py", line 138, in run
    self.mainloop()
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/__init__.py", line 266, in mainloop
    plugin_class(args[2:], self.options).run() # all starts again there
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/__init__.py", line 138, in run
    self.mainloop()
  File "/var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/export/dump.py", line 210, in mainloop
    fileout = codecs.open(filepath, 'w', config.charset)
  File "/var/www/wiki.ros.org/venv/lib64/python2.6/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 36] File name too long: '/tmp/test_dump/output/Tutorials(2f)Landing(20)an(20)autonomous(20)UAV(20)on(20)a(20)moving(20)platform(20)using(20)only(20)a(20)front(20)facing(20)camera(2f)Landing(20)an(20)autonomous(20)UAV(20)on(20)a(20)moving(20)platform(20)using(20)only(20)a(20)front(20)facing(20)camera.html'
```

**Comment by tfoote** [comment]
There was a tutorial made accidentally with the doubly long wiki page name: 

Tutorials/Landing an autonomous UAV on a moving platform using only a front facing camera
Tutorials/Landing an autonomous UAV on a moving platform using only a front facing camera/Landing an autonomous UAV on a moving platform using only a front facing camera

**Comment by tfoote** [comment]
I've resolved this by deleting the super long page. And have kicked off another export. 

I looked and I couldn't find a way to set the wiki to limit title length.
This is something that the export could catch and continue skipping that one page. The export even catches `Ctrl-C` for each page.

I also deleted the link here so someone doesn't accidentially recreate it by clicking on it.

**Comment by tfoote** [comment]
Confirmed that with their next sync the mirrors are getting the full content back. Such as http://mirror-eu.wiki.ros.org/Distributions.html
